// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMZqgzihSv8D4O8LddxRxNKirAfLUpkpo',
    appId: '1:522989060345:web:c6e8ba1d0680300a172228',
    messagingSenderId: '522989060345',
    projectId: 'taskbunny-58049',
    authDomain: 'taskbunny-58049.firebaseapp.com',
    storageBucket: 'taskbunny-58049.appspot.com',
    measurementId: 'G-NLD1S43RPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5RlCplx41bLTeKQfHAIrioU79qGBpEfs',
    appId: '1:522989060345:android:06ccb0705d198e5d172228',
    messagingSenderId: '522989060345',
    projectId: 'taskbunny-58049',
    storageBucket: 'taskbunny-58049.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVCorrwBFOqVblCZlIbYNNu3INFy3jKK8',
    appId: '1:522989060345:ios:a2b7e43efda1a87e172228',
    messagingSenderId: '522989060345',
    projectId: 'taskbunny-58049',
    storageBucket: 'taskbunny-58049.appspot.com',
    iosBundleId: 'com.example.taskbunny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVCorrwBFOqVblCZlIbYNNu3INFy3jKK8',
    appId: '1:522989060345:ios:a2b7e43efda1a87e172228',
    messagingSenderId: '522989060345',
    projectId: 'taskbunny-58049',
    storageBucket: 'taskbunny-58049.appspot.com',
    iosBundleId: 'com.example.taskbunny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMZqgzihSv8D4O8LddxRxNKirAfLUpkpo',
    appId: '1:522989060345:web:089660252a4cc59a172228',
    messagingSenderId: '522989060345',
    projectId: 'taskbunny-58049',
    authDomain: 'taskbunny-58049.firebaseapp.com',
    storageBucket: 'taskbunny-58049.appspot.com',
    measurementId: 'G-4SXPF644H3',
  );
}
